var FOURSQUARE_VENUE_URL = 'https://d310g5te00bhi.cloudfront.net/v2/venues/'
var FOURSQUARE_CREDS = '\?client_id\=FNJEOV4QV4YBMJ4J5EQNKQTCQXOQBCUSIIYIZAXWMKLY5XPN\&client_secret\=NEKCZ4IFX4SOJEPDY2E1ZIV4NTAYZ3GWQHWKKPSQF3KOZKCS\&v\=20140806\&m\=foursquare';

module.exports.FOURSQUARE_VENUE_URL = FOURSQUARE_VENUE_URL;
module.exports.FOURSQUARE_CREDS = FOURSQUARE_CREDS;


